#!/usr/bin/env python
import glob

evus = 0
atkus = 0
swengus = 0
histia = 0
detha = 0
balthus = 0
regia = 0
darkus = 0
angilsa = 0
knox = 0
rodnus = 0
eva = 0
respia = 0
sespus = 0
faustus = 0
awaria = 0
horus = 0
proximus = 0
sprite = 0
sylpha = 0
virgil = 0
sartorio = 0
an = 0
mentus = 0
bodrus = 0
spirtus = 0
pathfind = 0
loomva = 0
skea = 0
dentir = 0
troilus = 0
chronos = 0
quantos = 0
respos = 0
sespos = 0
radia = 0
pontifen = 0
bouste = 0
seel = 0
skryss = 0
alaenos = 0
histurvia = 0
hardio = 0
oossla = 0
leladar = 0
lalerad = 0
ittum = 0
tykan = 0
energy = 0
lumi = 0
salve = 0
catsbane = 0
phantasm = 0
partroon = 0
halfling = 0
sylvan = 0
dwarven = 0
frrinakin = 0
vorharn = 0
bracis = 0
bloodblade= 0
fellblade = 0
gossamer = 0
zeucros = 0
bruia = 0
atkia = 0
zehnt = 0
bangus = 0
ranger2 = 0
duvin = 0
farly = 0
respin = 0
splash = 0
tracking = 0
heen = 0
nomoss = 0
blooddecay = 0
felldecay = 0
gossdecay = 0
channel = 0
toomeria = 0
corsetta = 0
forgus = 0
vala = 0

logfiles = glob.glob("*.txt")
for logfile in logfiles:
        file = open(logfile, encoding="ISO-8859-1")
        data = file.read()
                evus += data.count("You seem to fight more effectively now")
        atkus += data.count("You seem to attack more precisely now")
        swengus += data.count("You notice your balance and recovery improving")
        histia += data.count("You seem to be able to take more damage now")
        detha += data.count("You seem to be defending yourself better")
        balthus += data.count("You notice your balance improving")
        regia += data.count("You notice your balance recovering more quickly")
        regia += data.count("You seem to notice your balance regenerating faster")
        darkus += data.count("You notice yourself dealing more damage")
        angilsa += data.count("You notice your balance recovering much more quickly")
        knox += data.count("You notice yourself dealing much more damage")
        rodnus += data.count("You feel more receptive to healing")
        eva += data.count("You seem to heal more effectively")
        respia += data.count("You seem to recover spiritual energy faster")
        sespus += data.count("You notice that you can use your healing ability longer")
        sespus += data.count("You notice that you can use your moonstone longer")
        faustus += data.count("You notice yourself healing others faster")
        awaria += data.count("You seem to heal yourself more easily with the moonstone")
        horus += data.count("You seem to heal people closer to death now")
        proximus += data.count("You seem to heal from further away now")
        sprite += data.count("Your healing spirit improves")
        sylpha += data.count("You understand the walking self-heal technique better")
        virgil += data.count("You have more purgatory pendant knowledge")
        sartorio += data.count("You notice yourself keeping people in stitches better")
        an += data.count("You notice yourself recovering your energy and healing others faster")
        mentus += data.count("Your mind seems keener")
        bodrus += data.count("Your body feels stronger")
        spirtus += data.count("Your spirit improves")
        pathfind += data.count("Your eye grows keener")
        pathfind += data.count("You feel better able to spot hidden passages")
        loomva += data.count("You learn how to maintain your equipment better")
        loomva += data.count("You learn how to maintain your tools")
        skea += data.count("Your study of skinning seems to be paying off")
        dentir += data.count("Your study of mandible extraction seems to be taking root")
        troilus += data.count("You feel yourself recuperating faster")
        chronos += data.count("You notice your augment lasting longer")
        quantos += data.count("You notice that you can augment others to a greater degree")
        quantos += data.count("You notice that you&apos;re able to increase others&apos; balance more")
        respos += data.count("You feel your mind recovering faster")
        sespos += data.count("You feel your mind lasting longer now")
        radia += data.count("You notice your augmentation reaching further")
        pontifen += data.count("You notice that you&apos;re able to increase others&apos; accuracy more")
        bouste += data.count("You notice that you can enhance others to a greater degree")
        seel += data.count("Things appear a bit more clearly, now")
        skryss += data.count("You feel more aware of others")
        alaenos += data.count("You feel more in tune with your surroundings now")
        histurvia += data.count("You feel able to take more damage now")
        hardio += data.count("Your body feels a little stronger")
        oossla += data.count("You feel that you know the other exiles better")
        leladar += data.count("You understand the flow of ether a little better")
        lalerad += data.count("You understand the flow of ethereal amulet a little better")
        lalerad += data.count("You understand the flow of ethereal something.. a little better")
        ittum += data.count("Your Atkite Channeling improves")
        tykan += data.count("You feel closer to understanding how to make a tykan healing potion")
        energy += data.count("You feel closer to understanding how to make a potion of energy")
        lumi += data.count("You feel closer to understanding how to make a luminescent culture")
        salve += data.count("You feel closer to understanding how to make a luminescent salve")
        catsbane += data.count("You feel closer to understanding how to make a catsbane necklace")
        phantasm += data.count("Your phantasmological skills appear to be stronger")
        partroon += data.count("You feel closer to understanding the Thoomish language")
        halfling += data.count("You feel closer to understanding the language of the Halfling")
        sylvan += data.count("You feel closer to understanding the Sylvan language")
        dwarven += data.count("You feel closer to understanding the Dwarven language")
        frrinakin += data.count("You feel closer to understanding the language of the People")
        vorharn += data.count("You feel closer to understanding the Ghorak Zo language")
        bracis += data.count("You feel less dependent on normal weapons")
        bloodblade += data.count("You learn how to better utilize your bloodblade")
        fellblade += data.count("You learn how to better utilize your fell blade")
        gossamer += data.count("You learn how to better utilize your gossamer")
        zeucros += data.count("You feel more skilled in the art of baking")
        bruia += data.count("You feel more skilled in the art of brewing")
        atkia += data.count("Your attack is more accurate and able")
        zehnt += data.count("You seem to recover Earthpower faster")
        bangus += data.count("Your combat ability improves")
        ranger2 += data.count("You become more mindful of the power of surprise")
        ranger2 += data.count("You gain insight into the strength of solitude")
        duvin += data.count("Your study of creatures is progressing")
        ranger2 += data.count("You gain a deeper understanding of camouflage")
        farly += data.count("You seem tougher")
        respin += data.count("You learn to channel energy from the world more efficiently")
        splash += data.count("Your ability to store energy from the world improves")
        tracking += data.count("Your understanding of tracking grows")
        ranger2 += data.count("You become more attuned to the strength of coordination")
        heen += data.count("Your study of the shieldstone is improving")
        farly += data.count("You feel tougher")
        nomoss += data.count("Your stonegirdle movement knowledge increases")
        blooddecay += data.count("You lose some of your grasp of blood magic")
        felldecay += data.count("You lose some of your grasp of backstabbing")
        gossdecay += data.count("You lose some of your grasp of controlled swings")
        gossdecay += data.count("You lose some of your grasp of controlled attacks")
        channel += data.count("Your Earthpower Channeling improves")
        toomeria += data.count("Your Earthpower improves")
        corsetta += data.count("Your stonegirdle ability improves")
        forgus += data.count("Your knowledge of blacksmithing improves")
        vala += data.count("Your lava cloak ability improves")

if evus != 0: print('Evus:', evus)
if atkus != 0: print('Atkus:', atkus)
if swengus != 0: print('Swengus:', swengus)
if histia != 0: print('Histia:', histia)
if detha != 0: print('Detha:', detha)
if balthus != 0: print('Balthus :', balthus )
if regia != 0: print('Regia :', regia )
if darkus != 0: print('Darkus:', darkus)
if angilsa != 0: print('Angilsa:', angilsa)
if knox != 0: print('Knox:', knox)
if rodnus != 0: print('Rodnus:', rodnus)
if eva != 0: print('Eva:', eva)
if respia != 0: print('Respia:', respia)
if sespus != 0: print('Sespus:', sespus)
if faustus != 0: print('Faustus:', faustus)
if awaria != 0: print('Awaria:', awaria)
if horus != 0: print('Horus:', horus)
if proximus != 0: print('Proximus:', proximus)
if sprite != 0: print('Sprite:', sprite)
if sylpha != 0: print('Sylpha:', sylpha)
if virgil != 0: print('Virgil:', virgil)
if sartorio != 0: print('Sartorio:', sartorio)
if an != 0: print('An:', an)
if mentus != 0: print('Mentus:', mentus)
if bodrus != 0: print('Bodrus:', bodrus)
if spirtus != 0: print('Spirtus:', spirtus)
if pathfind != 0: print('Pathfinding:',  pathfind)
if loomva != 0: print('Loomva:', loomva)
if skea != 0: print('Skea:',  skea)
if dentir != 0: print('Dentir:', dentir)
if troilus != 0: print('Troilus:',  troilus)
if chronos != 0: print('Chronos:', chronos)
if quantos != 0: print('Quantos:', quantos)
if respos != 0: print('Respos:', respos)
if sespos != 0: print('Sespos:', sespos)
if radia != 0: print('Radia:', radia)
if pontifen != 0: print('Pontifen:', pontifen)
if bouste != 0: print('Bouste:', bouste)
if seel != 0: print('Seel:', seel)
if skryss != 0: print('Skryss:', skryss)
if alaenos != 0: print('Alaenos:', alaenos)
if histurvia != 0: print('Histurvia:', histurvia)
if hardio != 0: print('Hardio:', hardio)
if oossla != 0: print('Oossla:', oossla)
if leladar != 0: print('Leladar:', leladar)
if lalerad != 0: print('Lalerad:', lalerad)
if ittum != 0: print('Ittum:', ittum)
if tykan != 0: print('Tykan:', tykan)
if energy != 0: print('Energy Potion:', energy)
if lumi != 0: print('Luminescent Culture:', lumi)
if salve != 0: print('Luminescent Salve:', salve)
if catsbane != 0: print('Catsbane Necklace:', catsbane)
if phantasm != 0: print('Phantasm:', phantasm)
if partroon != 0: print('ParTroon:', partroon)
if halfling != 0: print('Halfling:', halfling)
if sylvan != 0: print('Sylvan:', sylvan)
if dwarven != 0: print('Dwarven:', dwarven)
if frrinakin != 0: print('Frrinakin:', frrinakin)
if vorharn != 0: print('Vorharn:', vorharn)
if bracis != 0: print('Bracis:', bracis)
if bloodblade != 0: print('Bloodblade:', bloodblade)
if fellblade != 0: print('Fellblade:', fellblade)
if gossamer != 0: print('Gossamer:', gossamer)
if zeucros != 0: print('Zeucros:', zeucros)
if bruia != 0: print('Bruia:', bruia)
if atkia != 0: print('Atkia:', atkia)
if zehnt != 0: print('Zehnt:', zehnt)
if bangus != 0: print('Bangus Anmash:', bangus)
if ranger2 != 0: print('Ranger 2nd Slot:', ranger2)
if duvin != 0: print('Duvin:', duvin)
if farly != 0: print('Farly:', farly)
if respin != 0: print('Respin:', respin)
if splash != 0: print('Splash:', splash)
if tracking != 0: print('Tracking:', tracking)
if heen != 0: print('Heen:', heen)
if nomoss != 0: print('Nomoss:', nomoss)
if blooddecay != 0: print('Bloodblade Decay:', blooddecay)
if felldecay != 0: print('Fellblade Decay:', felldecay)
if gossdecay != 0: print('Gossamer Decay:', gossdecay)
if channel != 0: print('Channel Master:', channel)
if toomeria != 0: print('Toomeria:', toomeria)
if corsetta != 0: print('Corsetta:', corsetta)
if forgus != 0: print('Forgus:', forgus)
if vala != 0: print('Vala:', vala)
